#!/bin/bash -eu

set -o pipefail

readonly VERSION="${1:?}"

cd "$(jj root)"

if jj show --stat | tail -n -1 | grep -q '^0 files changed'
then
  jj describe -m "chore: version ${VERSION}"
else
  jj new -m "chore: version ${VERSION}"
fi

cargo set-version "${VERSION}"

cargo upgrade
cargo update

cargo check
cargo test

git cliff --tag "${VERSION}" | head -n -3 > CHANGELOG.md

jj new
jj tag set -r @- "${VERSION}"
